[catalog]
name = "Gitspace Official Catalog"
description = "Official catalog of plugins and templates for Gitspace"
version = "2024.09.29"
last_updated = { date = "2024-09-25T18:37:40Z", commit_hash = "placeholder_hash" }

[plugins]
[plugins.scmtea]
version = "1.0.0"
description = "Gitea local container management"
path = "plugins/scmtea"

[templates]
[templates.gitspace-plugin-starter]
version = "0.1.0"
description = "A starter template for creating a Gitspace plugin"
path = "templates/gitspace-plugin-starter"

[templates.gitspace-catalog-starter]
path = "templates/gitspace-catalog-starter"
version = "0.1.0"
description = "A starter template for creating a Gitspace catalog"

