[catalog]
last_updated = { date = "2024-09-25T22:37:19Z", commit_hash = "placeholder_hash" }
name = "Gitspace Official Catalog"
description = "Official catalog of plugins and templates for Gitspace"
version = "2024.09.30"

[plugins]
[plugins.scmtea]
path = "plugins/scmtea"
version = "1.0.0"
description = "Gitea local container management"

[templates]
[templates.gitspace-catalog-starter]
version = "0.1.0"
description = "A starter template for creating a Gitspace catalog"
path = "templates/gitspace-catalog-starter"

[templates.gitspace-plugin-starter]
path = "templates/gitspace-plugin-starter"
version = "0.1.0"
description = "A starter template for creating a Gitspace plugin"

