[catalog]
last_updated = { date = "2024-09-19T04:11:13Z", commit_hash = "placeholder_hash" }
name = "Gitspace Official Catalog"
description = "Official catalog of plugins and templates for Gitspace"
version = "0.1.13"

[plugins]
[plugins.templater]
path = "plugins/templater"
version = "0.2.0"
description = "Template manager for gitspace"

[templates]
[templates.gitspace-catalog-starter]
description = "A starter template for creating a Gitspace catalog"
path = "templates/gitspace-catalog-starter"
version = "0.1.0"

[templates.gitspace-plugin-starter]
version = "0.1.0"
description = "A starter template for creating a Gitspace plugin"
path = "templates/gitspace-plugin-starter"

