[catalog]
last_updated = { date = "2024-09-13T00:31:08Z", commit_hash = "placeholder_hash" }
name = "Gitspace Official Catalog"
description = "Official catalog of plugins and templates for Gitspace"
version = "0.1.3"

[plugins]
[plugins.templater]
version = "0.1.0"
description = "A Gitspace plugin"
path = "plugins/templater"

[templates]
[templates.gitspace-catalog-starter]
path = "templates/gitspace-catalog-starter"

[templates.gitspace-plugin-starter]
version = "0.1.0"
description = "A Gitspace plugin"
path = "templates/gitspace-plugin-starter"

