[catalog]
description = "Official catalog of plugins and templates for Gitspace"
version = "2024.09.34"
last_updated = { date = "2024-10-01T02:32:08Z", commit_hash = "placeholder_hash" }
name = "Gitspace Official Catalog"

[plugins]
[plugins.scmtea]
version = "1.0.0"
description = "Gitea local container management"
path = "plugins/scmtea"

[templates]
[templates.gitspace-catalog-starter]
version = "0.1.0"
description = "A starter template for creating a Gitspace catalog"
path = "templates/gitspace-catalog-starter"

[templates.gitspace-plugin-starter]
path = "templates/gitspace-plugin-starter"
version = "0.1.0"
description = "A starter template for creating a Gitspace plugin"

