[catalog]
description = "Official catalog of plugins and templates for Gitspace"
version = "2024.09.33"
last_updated = { date = "2024-09-27T18:46:09Z", commit_hash = "placeholder_hash" }
name = "Gitspace Official Catalog"

[plugins]
[plugins.scmtea]
description = "Gitea local container management"
path = "plugins/scmtea"
version = "1.0.0"

[templates]
[templates.gitspace-catalog-starter]
description = "A starter template for creating a Gitspace catalog"
path = "templates/gitspace-catalog-starter"
version = "0.1.0"

[templates.gitspace-plugin-starter]
path = "templates/gitspace-plugin-starter"
version = "0.1.0"
description = "A starter template for creating a Gitspace plugin"

