[catalog]
last_updated = { date = "2024-09-25T00:03:39Z" }
name = "Gitspace Official Catalog"
description = "Official catalog of plugins and templates for Gitspace"
version = "2024.09.24"

[plugins]
[plugins.templater]
version = "2024.09.24"
description = "Template manager for gitspace"
path = "plugins/templater"

[templates]
[templates.gitspace-catalog-starter]
path = "templates/gitspace-catalog-starter"
version = "2024.09.24"
description = "A starter template for creating a Gitspace catalog"

[templates.gitspace-plugin-starter]
version = "2024.09.24"
description = "A starter template for creating a Gitspace plugin"
path = "templates/gitspace-plugin-starter"

