name: Update Catalog

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'plugins/**'
      - 'templates/**'

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Install Dagger
        run: |
          cd /usr/local
          curl -L https://dl.dagger.io/dagger/install.sh | sh
          cd -

      - name: Run Dagger pipeline
        run: go run ./cmd/dagger-pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
